# -*- coding: utf-8 -*-
"""CE807_assignment_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Hzhy9_uKQfJvdSBkrlEJ6bPowTgYelk

# Student ID: 2501488

**Your student_id is your 7/8 digit FASER number.**

This is a sample format for CE807: Assignment. You must follow the format.
The code will have three broad sections, and additional sections if needed:

1. **Common Codes** — shared utilities, paths, metrics, I/O helpers
2. **Method Unsupervised (LLM Prompting)** — `train_unsup` / `test_unsup`
3. **Method Discriminative (Logistic Regression)** — `train_dis` / `test_dis`
4. **Main Execution** — orchestrates training and testing end-to-end

**You must have `train_unsup`, `test_unsup` for Unsupervised method and `train_dis`, `test_dis` for Discriminative method. This will be evaluated automatically.**

Code should be properly indented, print as much as possible, and follow standard PEP 8 coding and documentation practices.

Install Required Libraries
All dependencies are installed automatically below.
"""

# Install all required libraries automatically.
import subprocess, sys

def _pip(*pkgs):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *pkgs])

_pip("transformers>=4.38.0", "torch>=2.0.0", "sentencepiece", "accelerate")
_pip("scikit-learn>=1.3.0", "nltk", "gdown", "pandas", "numpy")
print("\u2713 All libraries installed.")

"""Import Libraries
All required libraries are imported below.
"""

# ── Standard library ──
import os, sys, pickle, random, warnings
from pathlib import Path

warnings.filterwarnings("ignore")

# ── Numeric / Data ──
import numpy as np
import pandas as pd

# ── NLP preprocessing ──
import nltk
nltk.download("stopwords",  quiet=True)
nltk.download("wordnet",    quiet=True)
nltk.download("punkt",      quiet=True)
nltk.download("punkt_tab",  quiet=True)
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

# ── Scikit-learn ──
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import (accuracy_score, f1_score,
                             classification_report, confusion_matrix)
from sklearn.pipeline import Pipeline

# ── PyTorch + HuggingFace (as required) ──
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# ── File download ──
import gdown

print("\u2713 All imports successful.")

"""**Set student ID and dataset ID**"""

student_id = 2501488   # integer, used as seed and folder name
DATA_ID    = 71          # dataset number assigned on Moodle

"""Set `seed` for all libraries — student ID is used as seed for reproducibility."""

def set_global_seed(seed: int) -> None:
    """Set seeds for Python, NumPy, and PyTorch (CPU + CUDA)."""
    random.seed(seed)
    np.random.seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark     = False
    print(f"\u2713 Global seed set to {seed}")

set_global_seed(student_id)

"""`train_unsup()`
`test_unsup()`
`train_dis()`
`test_dis()`

# Common Codes

This section contains all shared utilities:
- Path configuration (Google Drive + data / model dirs)
- Data reading
- Performance metrics
- Dataset statistics
- Model save / load (with Google Drive auto-download)

### Path Configuration
Mount Google Drive and set all global path variables.
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# ─────────────────────────────────────────────────────────────────────────────
# Path Configuration
# ─────────────────────────────────────────────────────────────────────────────

GOOGLE_DRIVE_PATH_AFTER_MYDRIVE = 'CE807-26-SP/Assignment/'
GOOGLE_DRIVE_PATH = os.path.join('drive', 'MyDrive', GOOGLE_DRIVE_PATH_AFTER_MYDRIVE)
print('Drive base path:', GOOGLE_DRIVE_PATH)
print('Files in base path:', os.listdir(GOOGLE_DRIVE_PATH))

# Google Drive URLs for auto-downloading saved model artefacts.
# After training, upload model files to Drive and paste shareable links here.
GDRIVE_URLS = {
    "lr_model.sav"      : "https://drive.google.com/uc?id=1WEWjO26wvqDifDmM3oJKi6rMMhsF6hk3",
    "lr_vectorizer.sav" : "https://drive.google.com/uc?id=1Jn6RUEEVzeb1QAz-MDtXCJxTkTaWVK_s",
    "lr_config.sav"     : "https://drive.google.com/uc?id=1kcgrXqoUx1t7_IHIgfFZApSG4YBQjh0-",
    "best_llm.txt"      : "https://drive.google.com/uc?id=1SVes8nR3AEJ-2sAenKdgYtfBKjcWRACF",
}

# Data and model paths
DATA_PATH    = os.path.join(GOOGLE_DRIVE_PATH, 'data', str(DATA_ID))
train_file   = os.path.join(DATA_PATH, 'train.csv')
val_file     = os.path.join(DATA_PATH, 'valid.csv')
test_file    = os.path.join(DATA_PATH, 'test.csv')

MODEL_PATH              = os.path.join(GOOGLE_DRIVE_PATH, 'model', str(student_id))
MODEL_Dis_DIRECTORY     = os.path.join(MODEL_PATH, 'Model_Dis')
MODEL_unsup_DIRECTORY   = os.path.join(MODEL_PATH, 'Model_Unsup')

os.makedirs(DATA_PATH,            exist_ok=True)
os.makedirs(MODEL_Dis_DIRECTORY,  exist_ok=True)
os.makedirs(MODEL_unsup_DIRECTORY, exist_ok=True)

print('Train file      :', train_file)
print('Validation file :', val_file)
print('Test file       :', test_file)
print('LR model dir    :', MODEL_Dis_DIRECTORY)
print('LLM model dir   :', MODEL_unsup_DIRECTORY)

# Read train Data
train_df = pd.read_csv(train_file)
train_df

# Read Validation Data
val_df = pd.read_csv(val_file)
val_df

"""### Data Reading
A helper function to load a CSV and print basic info.
"""

def read_data(file_path: str) -> pd.DataFrame:
    df = pd.read_csv(file_path)
    print(f"  Loaded : {file_path}  \u2192  {len(df):,} rows, {df.shape[1]} columns")
    return df

test_df = read_data(test_file)

"""### Performance Metrics
Compute Accuracy, Macro-F1, Weighted-F1, per-class F1, and Confusion Matrix.
"""

def compute_metrics(y_true, y_pred, label: str = "") -> dict:
    acc = accuracy_score(y_true, y_pred)
    mf1 = f1_score(y_true, y_pred, average="macro",    zero_division=0)
    wf1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)
    tag = f"[{label}] " if label else ""

    print(f"\n{tag}{'\u2500'*50}")
    print(f"  Accuracy    : {acc:.4f}")
    print(f"  Macro-F1    : {mf1:.4f}")
    print(f"  Weighted-F1 : {wf1:.4f}")
    print("\n" + classification_report(y_true, y_pred, zero_division=0))
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred))
    return {"accuracy": acc, "macro_f1": mf1, "weighted_f1": wf1}

"""### Dataset Statistics
Print label distribution and basic text-length statistics.
"""

def print_dataset_statistics(df: pd.DataFrame, name: str = "Dataset") -> None:
    print(f"\n{'='*55}")
    print(f"  {name}  \u2014  {len(df):,} samples")
    print(f"{'='*55}")
    label_col = "sentiment" if "sentiment" in df.columns else ("rating" if "rating" in df.columns else None)
    if label_col:
        vc = df[label_col].value_counts()
        for lbl, cnt in vc.items():
            pct = 100 * cnt / len(df)
            print(f"  {str(lbl):10s}: {cnt:5d}  ({pct:5.1f}%)")
    lengths = df["text"].str.len()
    print(f"  Text length \u2014 mean: {lengths.mean():.1f}, "
          f"median: {lengths.median():.1f}, max: {lengths.max()}")
    print()

"""### Model Save / Load with Auto-Download
Pickle-based save/load with optional Google Drive auto-download when a local file is missing.
"""

def save_object(obj, path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        pickle.dump(obj, f)
    print(f"  Saved  \u2192 {path}")


def load_object(path: str, gdrive_url: str = None):
    fname = os.path.basename(path)
    if not os.path.exists(path):
        url = gdrive_url or GDRIVE_URLS.get(fname)
        if url and "REPLACE_WITH" not in url:
            print(f"  File not found locally. Downloading: {fname} \u2026")
            os.makedirs(os.path.dirname(path), exist_ok=True)
            gdown.download(url, path, quiet=False)
        else:
            raise FileNotFoundError(
                f"Model file '{path}' not found. "
                "Please set the correct Google Drive URL in GDRIVE_URLS."
            )
    with open(path, "rb") as f:
        return pickle.load(f)

"""# Method Unsupervised Start

Zero-shot / prompt-based sentiment classification using open-source Seq2Seq LLMs from HuggingFace.

**Pipeline:**
1. Compare flan-t5-small / base / large on a stratified validation sample.
2. Select the best-performing LLM.
3. Design and evaluate 5 distinct prompt strategies on the full validation set.
4. At test time, apply all 5 prompts and write `out_label_Prompt_1` to--> `out_label_Prompt_5`.

### Device & Model Setup
"""

def get_device() -> torch.device:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"  Using device: {device}")
    return device

"""### Prompt Templates
Five diverse prompt strategies for binary sentiment classification.

"""

PROMPTS = {
    #P1—Direct/Minimal
    "Prompt_1": (
        "Classify the sentiment of the following product review. "
        "Reply with exactly one word: positive or negative.\n"
        "Review: {text}\n"
        "Sentiment:"
    ),

    #P2—Explicit instruction with label definition
    "Prompt_2": (
        "You are a sentiment analysis system. "
        "A positive review expresses satisfaction; a negative review expresses dissatisfaction. "
        "Given the review below, output only 'positive' or 'negative'.\n"
        "Review: {text}\n"
        "Answer:"
    ),

    #P3—Few-shot (2 examples per class)
    "Prompt_3": (
        "Determine whether each product review is positive or negative.\n\n"
        "Example 1: 'This product is amazing, works perfectly!' \u2192 positive\n"
        "Example 2: 'Broke after one day, total waste of money.' \u2192 negative\n"
        "Example 3: 'Great value, very happy with the purchase.' \u2192 positive\n"
        "Example 4: 'Poor quality, does not match description.' \u2192 negative\n\n"
        "Now classify:\n"
        "Review: {text}\n"
        "Sentiment:"
    ),

    #P4—Role-based persona
    "Prompt_4": (
        "As an expert product reviewer, analyse the sentiment expressed in the "
        "following Amazon review. Provide a single-word answer: positive or negative.\n"
        "Review: {text}\n"
        "Sentiment:"
    ),

    #P5—Chain-of-thought (brief reasoning then label)
    "Prompt_5": (
        "Read the product review and decide whether the customer is satisfied (positive) "
        "or dissatisfied (negative). Think step by step: identify key sentiment words, "
        "then give a one-word verdict.\n"
        "Review: {text}\n"
        "Verdict:"
    ),
}

print(f"\u2713 {len(PROMPTS)} prompt templates defined.")
for k in PROMPTS:
    print(f"  {k}: {PROMPTS[k][:60].strip()} \u2026")

"""### Output Post-Processing
Convert raw LLM output to a clean positive/negative label.
"""

def parse_sentiment(raw_output: str) -> str:
    text = raw_output.strip().lower()
    if "negative" in text or "neg" in text or "bad" in text or "poor" in text:
        return "negative"
    if "positive" in text or "pos" in text or "good" in text or "great" in text:
        return "positive"
    tokens = text.split()
    if tokens:
        last = tokens[-1].strip(".,!?")
        if "neg" in last:
            return "negative"
    return "positive"

"""### Batch Prediction Utility
Run LLM inference over a list of texts using a given prompt template.
"""

def batch_predict(model, tokenizer, device, texts: list,
                  prompt_template: str, batch_size: int = 16) -> list:
    model.eval()
    preds = []
    for start in range(0, len(texts), batch_size):
        batch_texts = texts[start: start + batch_size]
        prompts = [prompt_template.format(text=t) for t in batch_texts]
        enc = tokenizer(
            prompts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=256,
        ).to(device)
        with torch.no_grad():
            out_ids = model.generate(
                **enc,
                max_new_tokens=10,
                num_beams=2,
                early_stopping=True,
            )
        decoded = tokenizer.batch_decode(out_ids, skip_special_tokens=True)
        preds.extend([parse_sentiment(d) for d in decoded])
    return preds

"""### LLM Comparison Function
Compare flan-t5-small, flan-t5-base, and flan-t5-large on a stratified validation sample.

"""

CANDIDATE_LLMS = [
    "google/flan-t5-small",   # ~80M params  — fast
    "google/flan-t5-base",    # ~250M params — balanced
    "google/flan-t5-large",   # ~780M params — accurate
]

def compare_llms(val_df: pd.DataFrame, sample_size: int = 150,
                 prompt_key: str = "Prompt_1") -> str:
    set_global_seed(student_id)
    device = get_device()

    pos = val_df[val_df["sentiment"] == "positive"].sample(
        min(sample_size // 2, (val_df["sentiment"] == "positive").sum()),
        random_state=student_id)
    neg = val_df[val_df["sentiment"] == "negative"].sample(
        min(sample_size // 2, (val_df["sentiment"] == "negative").sum()),
        random_state=student_id)
    sample = pd.concat([pos, neg]).sample(frac=1, random_state=student_id)
    y_true = sample["sentiment"].tolist()
    texts  = sample["text"].tolist()

    template = PROMPTS[prompt_key]
    results  = {}

    print(f"\n{'='*60}")
    print(f"  LLM Comparison  (sample={len(sample)}, prompt={prompt_key})")
    print(f"{'='*60}")

    for model_name in CANDIDATE_LLMS:
        print(f"\n  Loading {model_name} \u2026")
        try:
            tok = AutoTokenizer.from_pretrained(model_name)
            mdl = AutoModelForSeq2SeqLM.from_pretrained(model_name).to(device)
            bs  = 16 if device.type == "cuda" else 8
            preds = batch_predict(mdl, tok, device, texts, template, batch_size=bs)
            metrics = compute_metrics(y_true, preds, label=model_name)
            results[model_name] = metrics["macro_f1"]
            del mdl; torch.cuda.empty_cache() if torch.cuda.is_available() else None
        except Exception as exc:
            print(f"  \u2717 {model_name} failed: {exc}")
            results[model_name] = 0.0

    print(f"\n{'\u2500'*60}")
    print("  LLM Comparison Summary:")
    for name, score in sorted(results.items(), key=lambda x: -x[1]):
        print(f"    {name:35s}  Macro-F1 = {score:.4f}")
    best = max(results, key=results.get)
    print(f"\n  \u2713 Best LLM selected: {best}  (Macro-F1 = {results[best]:.4f})")
    return best

"""## Training Unsupervised Method Code
train_unsup loads train/val data, runs LLM comparison, selects the best LLM,
evaluates all 5 prompts on the full validation set, and saves artifacts to model_dir.

"""

def train_unsup(train_file: str, val_file: str, model_dir: str,
                best_llm: str = None,
                skip_llm_comparison: bool = False) -> None:
    print("\n" + "="*60)
    print("  TRAIN UNSUPERVISED (LLM Prompting)")
    print("="*60)

    train_df = read_data(train_file)
    val_df   = read_data(val_file)
    print_dataset_statistics(train_df, "Train")
    print_dataset_statistics(val_df,   "Validation")

    os.makedirs(model_dir, exist_ok=True)

    #Step 1: LLM Selection
    if skip_llm_comparison and best_llm:
        selected_llm = best_llm
        print(f"  LLM comparison skipped. Using: {selected_llm}")
    else:
        selected_llm = compare_llms(val_df, sample_size=150, prompt_key="Prompt_1")

    #Save selected LLM name
    llm_path = os.path.join(model_dir, "best_llm.txt")
    with open(llm_path, "w") as f:
        f.write(selected_llm)
    print(f"  Best LLM saved \u2192 {llm_path}")

    #Step 2: Prompt Evaluation on Full Validation Set
    print(f"\n{'='*60}")
    print(f"  Prompt Evaluation using {selected_llm}")
    print(f"{'='*60}")

    set_global_seed(student_id)
    device = get_device()
    tok = AutoTokenizer.from_pretrained(selected_llm)
    mdl = AutoModelForSeq2SeqLM.from_pretrained(selected_llm).to(device)

    y_true         = val_df["sentiment"].tolist()
    texts          = val_df["text"].tolist()
    bs             = 16 if device.type == "cuda" else 8
    prompt_results = {}

    for pkey, template in PROMPTS.items():
        print(f"\n  Evaluating {pkey} \u2026")
        preds   = batch_predict(mdl, tok, device, texts, template, batch_size=bs)
        metrics = compute_metrics(y_true, preds, label=pkey)
        prompt_results[pkey] = metrics

    #Summary table
    print(f"\n{'='*60}")
    print(f"  Prompt Evaluation Summary (Val set, n={len(val_df)})")
    print(f"  {'Prompt':<15} {'Accuracy':>10} {'Macro-F1':>10} {'Wtd-F1':>10}")
    print(f"  {'\u2500'*15} {'\u2500'*10} {'\u2500'*10} {'\u2500'*10}")
    for pkey, m in prompt_results.items():
        print(f"  {pkey:<15} {m['accuracy']:>10.4f} {m['macro_f1']:>10.4f} {m['weighted_f1']:>10.4f}")

    best_prompt = max(prompt_results, key=lambda k: prompt_results[k]["macro_f1"])
    print(f"\n  \u2713 Best prompt: {best_prompt} "
          f"(Macro-F1 = {prompt_results[best_prompt]['macro_f1']:.4f})")

    save_object(prompt_results, os.path.join(model_dir, "prompt_results.sav"))
    print("\n  \u2713 train_unsup complete.")

RUN_TRAIN_UNSUP = True   # Train LLM (compare LLMs, evaluate 5 prompts)
if RUN_TRAIN_UNSUP:
    train_unsup(train_file, val_file, MODEL_unsup_DIRECTORY,
                skip_llm_comparison=False)

"""## Testing Method Unsupervised Code
test_unsup loads the saved best LLM, applies all 5 prompts to the test set,
and adds out_label_Prompt_1 to --> out_label_Prompt_5 columns to test.csv.

"""

def test_unsup(test_file: str, model_dir: str) -> pd.DataFrame:
    print("\n" + "="*60)
    print("  TEST UNSUPERVISED (LLM Prompting)")
    print("="*60)

    # Load best LLM name
    llm_path = os.path.join(model_dir, "best_llm.txt")
    if not os.path.exists(llm_path):
        url = GDRIVE_URLS.get("best_llm.txt", "")
        if url and "REPLACE_WITH" not in url:
            print("  Downloading best_llm.txt from Google Drive \u2026")
            os.makedirs(model_dir, exist_ok=True)
            gdown.download(url, llm_path, quiet=False)
        else:
            raise FileNotFoundError(
                f"'{llm_path}' not found. Run train_unsup first "
                "or set GDRIVE_URLS['best_llm.txt']."
            )
    with open(llm_path) as f:
        selected_llm = f.read().strip()
    print(f"  Loaded LLM: {selected_llm}")

    test_df = read_data(test_file)
    texts   = test_df["text"].tolist()

    set_global_seed(student_id)
    device = get_device()
    tok = AutoTokenizer.from_pretrained(selected_llm)
    mdl = AutoModelForSeq2SeqLM.from_pretrained(selected_llm).to(device)
    bs  = 16 if device.type == "cuda" else 8

    for pkey, template in PROMPTS.items():
        col = f"out_label_{pkey}"
        print(f"  Running {pkey} \u2192 {col} \u2026")
        preds = batch_predict(mdl, tok, device, texts, template, batch_size=bs)
        test_df[col] = preds
        vc = pd.Series(preds).value_counts()
        print(f"    Distribution: {dict(vc)}")

    out_path = os.path.join(os.path.dirname(test_file), "test.csv")
    test_df.to_csv(out_path, index=False)
    print(f"\n  \u2713 Predictions saved \u2192 {out_path}")
    print(f"  Columns: {[c for c in test_df.columns if 'out_label' in c]}")
    return test_df

RUN_TEST_UNSUP  = True   # Test  LLM
if RUN_TEST_UNSUP:
    test_unsup(test_file, MODEL_unsup_DIRECTORY)

"""## Method Unsupervised End

# Method Discriminative Start

TF-IDF + Logistic Regression with systematic grid search over:
- 4 text pre-processing strategies (basic, stop-word removal, stemming, lemmatisation)
- 2 n-gram ranges ((1,1) and (1,2))
- 3 regularisation values (C {0.1, 1.0, 10.0})

Total: **24 configurations** evaluated on the validation set.

### Text Pre-processing Functions
Four progressively more aggressive cleaning strategies.
"""

_STOP_WORDS  = set(stopwords.words("english"))
_STEMMER     = PorterStemmer()
_LEMMATIZER  = WordNetLemmatizer()


def preprocess_basic(text: str) -> str:
    return str(text).lower().strip()


def preprocess_stopwords(text: str) -> str:
    text = str(text).lower().strip()
    tokens = [t for t in text.split() if t.isalpha() and t not in _STOP_WORDS]
    return " ".join(tokens)


def preprocess_stemming(text: str) -> str:
    text = str(text).lower().strip()
    tokens = [
        _STEMMER.stem(t)
        for t in text.split()
        if t.isalpha() and t not in _STOP_WORDS
    ]
    return " ".join(tokens)


def preprocess_lemmatize(text: str) -> str:
    text = str(text).lower().strip()
    tokens = [
        _LEMMATIZER.lemmatize(t)
        for t in text.split()
        if t.isalpha() and t not in _STOP_WORDS
    ]
    return " ".join(tokens)


PREPROCESS_FNS = {
    "basic"      : preprocess_basic,
    "stopwords"  : preprocess_stopwords,
    "stemming"   : preprocess_stemming,
    "lemmatize"  : preprocess_lemmatize,
}

print(f"\u2713 {len(PREPROCESS_FNS)} preprocessing functions registered:",
      list(PREPROCESS_FNS.keys()))

"""### TF-IDF Builder
Fit a TF-IDF vectorizer with sublinear TF scaling.
"""

def build_tfidf(train_texts: list, ngram_range: tuple = (1, 1),
                max_features: int = 60_000) -> TfidfVectorizer:

    vec = TfidfVectorizer(
        ngram_range   = ngram_range,
        max_features  = max_features,
        sublinear_tf  = True,
        strip_accents = "unicode",
        analyzer      = "word",
        min_df        = 2,
    )
    vec.fit(train_texts)
    print(f"  TF-IDF fitted: ngram={ngram_range}, "
          f"vocab_size={len(vec.vocabulary_):,}")
    return vec

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, f1_score

"""## Training Method Discriminative Code
train_dis performs a 24-configuration grid search (4 preprocessing, 2 n-grams and 3 C values),
retrains the best config on the full training set, and saves artefacts to model_dir.

"""

def train_dis(train_file: str, val_file: str, model_dir: str) -> None:
    print("\n" + "="*60)
    print("  TRAIN DISCRIMINATIVE (Logistic Regression + TF-IDF)")
    print("="*60)

    train_df = read_data(train_file)
    val_df   = read_data(val_file)
    print_dataset_statistics(train_df, "Train")
    print_dataset_statistics(val_df,   "Validation")

    os.makedirs(model_dir, exist_ok=True)

    X_train_raw = train_df["text"].tolist()
    y_train     = train_df["sentiment"].tolist()
    y_val       = val_df["sentiment"].tolist()
    X_val_raw   = val_df["text"].tolist()

    #Grid Search
    grid_results = []
    ngram_ranges = [(1, 1), (1, 2)]
    C_values     = [0.1, 1.0, 10.0]

    print(f"\n  Grid search: {len(PREPROCESS_FNS)} preprocessing \u00d7 "
          f"{len(ngram_ranges)} n-gram \u00d7 {len(C_values)} C "
          f"= {len(PREPROCESS_FNS)*len(ngram_ranges)*len(C_values)} configs")
    print(f"  {'#':>3}  {'Preprocess':>12}  {'N-gram':>7}  {'C':>6}  "
          f"{'Acc':>8}  {'MacroF1':>9}  {'WtdF1':>8}")
    print(f"  {'\u2500'*3}  {'\u2500'*12}  {'\u2500'*7}  {'\u2500'*6}  "
          f"{'\u2500'*8}  {'\u2500'*9}  {'\u2500'*8}")

    cfg_num = 0
    for prep_name, prep_fn in PREPROCESS_FNS.items():
        X_tr = [prep_fn(t) for t in X_train_raw]
        X_vl = [prep_fn(t) for t in X_val_raw]
        for ngram in ngram_ranges:
            vec     = build_tfidf(X_tr, ngram_range=ngram)
            Xtr_vec = vec.transform(X_tr)
            Xvl_vec = vec.transform(X_vl)
            for C in C_values:
                cfg_num += 1
                set_global_seed(student_id)
                clf = LogisticRegression(
                    C            = C,
                    max_iter     = 1000,
                    solver       = "lbfgs",
                    class_weight = "balanced",
                    random_state = student_id,
                    multi_class  = "auto",
                )
                clf.fit(Xtr_vec, y_train)
                preds = clf.predict(Xvl_vec)
                acc   = accuracy_score(y_val, preds)
                mf1   = f1_score(y_val, preds, average="macro",    zero_division=0)
                wf1   = f1_score(y_val, preds, average="weighted", zero_division=0)
                grid_results.append({
                    "config"    : cfg_num,
                    "preprocess": prep_name,
                    "ngram"     : ngram,
                    "C"         : C,
                    "accuracy"  : acc,
                    "macro_f1"  : mf1,
                    "wtd_f1"    : wf1,
                })
                print(f"  {cfg_num:>3}  {prep_name:>12}  {str(ngram):>7}  "
                      f"{C:>6.1f}  {acc:>8.4f}  {mf1:>9.4f}  {wf1:>8.4f}")

    #Best configuration
    best = max(grid_results, key=lambda r: r["macro_f1"])
    print(f"\n  \u2713 Best config \u2192 Preprocess={best['preprocess']}, "
          f"N-gram={best['ngram']}, C={best['C']}, "
          f"Val Macro-F1={best['macro_f1']:.4f}")

    #Retrain best on full train set
    prep_fn   = PREPROCESS_FNS[best["preprocess"]]
    X_tr_best = [prep_fn(t) for t in X_train_raw]
    X_vl_best = [prep_fn(t) for t in X_val_raw]

    best_vec = build_tfidf(X_tr_best, ngram_range=best["ngram"])
    Xtr_best = best_vec.transform(X_tr_best)
    Xvl_best = best_vec.transform(X_vl_best)

    set_global_seed(student_id)
    best_clf = LogisticRegression(
        C            = best["C"],
        max_iter     = 1000,
        solver       = "lbfgs",
        class_weight = "balanced",
        random_state = student_id,
        multi_class  = "auto",
    )
    best_clf.fit(Xtr_best, y_train)

    print("\n  Final model \u2014 Validation set performance:")
    val_preds = best_clf.predict(Xvl_best)
    compute_metrics(y_val, val_preds, label="Best LR (Val)")

    #Save artifacts
    save_object(best_clf,     os.path.join(model_dir, "lr_model.sav"))
    save_object(best_vec,     os.path.join(model_dir, "lr_vectorizer.sav"))
    save_object(best,         os.path.join(model_dir, "lr_config.sav"))
    save_object(grid_results, os.path.join(model_dir, "lr_grid_results.sav"))

    print("\n  \u2713 train_dis complete.")

RUN_TRAIN_DIS   = True   # Train Logistic Regression (grid search)
if RUN_TRAIN_DIS:
    train_dis(train_file, val_file, MODEL_Dis_DIRECTORY)

"""## Testing Method Discriminative Code
`test_dis` loads saved LR artefacts (auto-download if missing) and predicts on the test set.
Adds `out_label_LR` column to `test.csv`.

"""

def test_dis(test_file: str, model_dir: str) -> pd.DataFrame:
    print("\n" + "="*60)
    print("  TEST DISCRIMINATIVE (Logistic Regression)")
    print("="*60)

    clf = load_object(os.path.join(model_dir, "lr_model.sav"),
                      GDRIVE_URLS.get("lr_model.sav"))
    vec = load_object(os.path.join(model_dir, "lr_vectorizer.sav"),
                      GDRIVE_URLS.get("lr_vectorizer.sav"))
    cfg = load_object(os.path.join(model_dir, "lr_config.sav"),
                      GDRIVE_URLS.get("lr_config.sav"))

    print(f"  Loaded LR model: preprocess={cfg['preprocess']}, "
          f"ngram={cfg['ngram']}, C={cfg['C']}")

    test_df = read_data(test_file)
    prep_fn = PREPROCESS_FNS[cfg["preprocess"]]
    X_test  = [prep_fn(t) for t in test_df["text"].tolist()]
    X_vec   = vec.transform(X_test)
    preds   = clf.predict(X_vec)

    test_df["out_label_LR"] = preds
    vc = pd.Series(preds).value_counts()
    print(f"  Predictions distribution: {dict(vc)}")

    out_path = os.path.join(os.path.dirname(test_file), "test.csv")
    test_df.to_csv(out_path, index=False)
    print(f"  \u2713 Predictions saved \u2192 {out_path}")
    return test_df

test_dis(test_file, MODEL_Dis_DIRECTORY)

RUN_TEST_DIS    = True   # Test  Logistic Regression \u2192 out_label_LR
if RUN_TEST_DIS:
    test_dis(test_file, MODEL_Dis_DIRECTORY)

"""## Discriminative Method End

# Other Method / Main Execution

Set the flags below to control which steps run.
For a fresh run, set all flags to `True`.
For submission evaluation, the auto-download will fetch models if not present locally.

## Output Verification
Confirm all required columns are present in `test.csv`.
"""

#Verify final test.csv
out_path = os.path.join(DATA_PATH, "test.csv")
final_df = pd.read_csv(out_path)

required_cols = [
    "out_label_LR",
    "out_label_Prompt_1",
    "out_label_Prompt_2",
    "out_label_Prompt_3",
    "out_label_Prompt_4",
    "out_label_Prompt_5",
]

print(f"\n{'='*60}")
print("  test.csv Final Column Check")
print(f"{'='*60}")
all_ok = True
for col in required_cols:
    present = col in final_df.columns
    status  = "\u2713" if present else "\u2717 MISSING"
    print(f"  {status}  {col}")
    if not present:
        all_ok = False

if all_ok:
    print("\n  \u2713 All required output columns present!")
else:
    print("\n  \u2717 Some columns are missing. Check the logs above.")

print(f"\n  Total test rows: {len(final_df):,}")
print("\n  Sample predictions (first 5 rows):")
display_cols = ["text"] + [c for c in required_cols if c in final_df.columns]
print(final_df[display_cols].head(5).to_string())

# Read Test Data
test_df = pd.read_csv(test_file)
test_df